name: 友链模板
description: 自助友链申请模板
labels: []
assignees:
  - deusyu
body:
  - type: markdown
    attributes:
      value: |
        ## 填写说明
        欢迎自助申请本站友链，**星号(*)为必填项**。审核通过后会实时同步到博客！
        > 申请前请先添加本站友链，谢谢！
         本站友链信息如下：
        - 博客名称：既往不恋
        - 博客地址：https://deusyu.app
        - 博客图标：https://deusyu.app/img/avatar-2023.png
        - 博客描述：Beauty will save the world.
        - 友链地址：https://deusyu.app/link/
        - 订阅地址：https://deusyu.app/atom.xml
  - type: checkboxes
    id: checks
    attributes:
      label: 检查清单
      description: 请认真检查以下清单中的每一项，并在相符的项前打勾。
      options:
        - required: true
          label: 合法的、非营利性、无商业广告、无木马植入。
        - required: false
          label: 有实质性原创内容的 HTTPS 站点，发布过至少 5 篇原创文章，且至少稳定运行半年。
        - required: false
          label: 无违反国家相关法律法规和道德底线的内容，不涉反动言论和政治敏感话题。
        - required: false
          label: 与 **博主** 有至少 2 次有效互动（有内容的留言或者 issue 等）。
  - type: input
    id: link-name
    attributes:
      label: 博客名称
      description: 请输入您的博客名称。
      placeholder: "如: 既往不恋"
    validations:
      required: true
  - type: input
    id: link-url
    attributes:
      label: 博客地址
      description: 请输入您博客的主页地址，包含https。
      placeholder: "如: https://deusyu.app"
    validations:
      required: true
  - type: input
    id: link-avatar
    attributes:
      label: 博客图标
      description: 请输入您博客的图标地址，包含https，请检查是否能正常访问，且无跨域问题。
      placeholder: "如: https://deusyu.app/img/avatar-2023.png"
    validations:
      required: true
  - type: input
    id: link-desc
    attributes:
      label: 博客描述
      description: 请输入您博客的描述。
      placeholder: "如: Beauty will save the world."
    validations:
      required: true
  - type: input
    id: friends-html
    attributes:
      label: 友链地址
      description: 请输入您的友链页面地址。
      placeholder: "如: https://yoursite.com/friends/"
    validations:
      required: false
  - type: input
    id: rss-url
    attributes:
      label: 订阅地址
      description: 如果您使用有RSS订阅链接，请在此处填写，方便抓取最新文章
      placeholder: "如: https://deusyu.app/atom.xml"
    validations:
      required: false
