name: Sync JSON Files to Private Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository (output branch)
        uses: actions/checkout@v4
        with:
          ref: output  # 指定为output分支
          path: public-repo
      - name: Checkout private repository (main branch)
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          ref: master
          token: ${{ secrets.GH_PAT }}
          path: private-repo
      - name: Setup Git
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}

      - name: Check if JSON file has changed
        id: file-check
        run: |
          if ! cmp -s public-repo/json/all.json private-repo/${{ secrets.PRIVATE_PATH }}/friendly.json; then
              echo "File has changed, need to sync."
              echo "::set-output name=sync_needed::true"
          else
              echo "File has not changed, no sync needed."
              echo "::set-output name=sync_needed::false"
          fi

      - name: Copy JSON files to private repository
        if: steps.file-check.outputs.sync_needed == 'true'
        run: |
          cp public-repo/json/all.json private-repo/${{ secrets.PRIVATE_PATH }}/friendly.json

      - name: Commit and Push changes to private repository
        if: steps.file-check.outputs.sync_needed == 'true'
        run: |
          cd private-repo
          git add .
          git diff-index --quiet HEAD || git commit -m "Update friendly.json on $(date +'%Y-%m-%d')"
          git push

